version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
after_build:
- cmd: nuget pack .\src\TypeScriptGenerator\TypeScriptDefinitionsGenerator.nuspec
